[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32@^6.12.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; Both communication backends are compiled in the same firmware.
; The active one is selected with robot_config::communication_type.
board_microros_distro = humble
board_microros_transport = serial
lib_deps =
    https://github.com/micro-ROS/micro_ros_platformio

build_flags =
    -std=gnu++17
    -DCORE_DEBUG_LEVEL=0
build_unflags =
    -std=gnu++11
