#include <cmath>
#include <cstdlib>
#include <iomanip>
#include <iostream>
#include <string>
#include <vector>
#include "diffnav.hpp"
using namespace diffnav;
struct SimRobot{OdometryConfig cfg{};DifferentialOdometry odom{cfg};float rd=0,ld=0,rv=0,lv=0;WheelSpeedController rc{},lc{};static constexpr float dt=.005f,tau=.055f;SimRobot(){odom.reset({},0,0);}void setPose(Pose2D p){odom.reset(p,rt(),lt());}int64_t rt()const{return std::llround(rd*cfg.counts_per_revolution/(cfg.right_wheel_diameter_mm*kPi));}int64_t lt()const{return std::llround(ld*cfg.counts_per_revolution/(cfg.left_wheel_diameter_mm*kPi));}static float motor(float pwm,float dead,float slope){return std::fabs(pwm)<=dead?0:signf(pwm)*(std::fabs(pwm)-dead)/slope;}void step(WheelSpeeds c){float rp=rc.update(c.right_mm_s,odom.state().wheel_speed.right_mm_s,dt),lp=lc.update(c.left_mm_s,odom.state().wheel_speed.left_mm_s,dt),tr=motor(rp,96,1.25f),tl=motor(lp,86,1.16f),a=dt/(tau+dt);rv+=a*(tr-rv);lv+=a*(tl-lv);rd+=rv*dt;ld+=lv*dt;odom.update(rt(),lt(),dt);}};
struct R{std::string name;bool pass;float t;Pose2D p;float pe,ae;};static float deg(float r){return r*180/kPi;}static bool run(SimRobot&r,Navigator&n,float timeout,float&time){time=0;for(int i=0;i<(int)(timeout/SimRobot::dt);i++){auto c=n.update(r.odom.state(),SimRobot::dt);r.step(c);time+=SimRobot::dt;if(!n.busy()){for(int j=0;j<20;j++)r.step({});return n.status().result==MotionResult::SUCCEEDED;}}return false;}
int main(){std::vector<R>v;{bool ok=extendLegacyPcntDelta(1200,1300)==100&&extendLegacyPcntDelta(29950,50)==100&&extendLegacyPcntDelta(-29950,-50)==-100&&extendLegacyPcntDelta(15100,14900)==-200;v.push_back({"pcnt_limit_extension",ok,0,{},0,0});}{OdometryConfig c;DifferentialOdometry o(c);o.reset({},0,0);auto rt=o.rightDistanceToTicks(400),lt=o.leftDistanceToTicks(200);o.update(rt,lt,.05f);float dr=o.rightTicksToDistance(rt),dl=o.leftTicksToDistance(lt),dc=.5f*(dr+dl),dt=(dr-dl)/c.track_width_mm,Rr=dc/dt,ex=Rr*std::sin(dt),ey=Rr*(1-std::cos(dt));auto p=o.state().pose;float e=std::hypot(p.x_mm-ex,p.y_mm-ey),a=std::fabs(p.theta_unwrapped_rad-dt);v.push_back({"odometry_exact_arc",e<.02f&&a<1e-5f,.05f,p,e,deg(a)});}{SimRobot r;Navigator n;n.commandMoveDistance(r.odom.state().pose,1000,500);float t;bool ok=run(r,n,8,t);auto p=r.odom.state().pose;float pe=std::hypot(p.x_mm-1000,p.y_mm),ae=std::fabs(wrapAngle(p.theta_rad));v.push_back({"forward_1000",ok&&pe<4&&ae<.03f,t,p,pe,deg(ae)});}{SimRobot r;Navigator n;n.commandMoveDistance(r.odom.state().pose,-600,380);float t;bool ok=run(r,n,7,t);auto p=r.odom.state().pose;float pe=std::hypot(p.x_mm+600,p.y_mm),ae=std::fabs(wrapAngle(p.theta_rad));v.push_back({"reverse_600",ok&&pe<4&&ae<.03f,t,p,pe,deg(ae)});}{SimRobot r;Navigator n;n.commandRotateRelative(r.odom.state().pose,kPi*.5f,250);float t;bool ok=run(r,n,5,t);auto p=r.odom.state().pose;float ae=std::fabs(wrapAngle(p.theta_rad-kPi*.5f));v.push_back({"rotate_90",ok&&ae<.02f,t,p,std::hypot(p.x_mm,p.y_mm),deg(ae)});}{SimRobot r;Navigator n;n.commandGoTo(r.odom.state().pose,700,500,450,1,true,kPi*.5f);float t;bool ok=run(r,n,10,t);auto p=r.odom.state().pose;float pe=std::hypot(p.x_mm-700,p.y_mm-500),ae=std::fabs(wrapAngle(p.theta_rad-kPi*.5f));v.push_back({"goto_final_heading",ok&&pe<5&&ae<.025f,t,p,pe,deg(ae)});}{SimRobot r;Navigator n;n.commandBezier(r.odom.state().pose,{250,0},{450,400},{750,400},360,1);float t;bool ok=run(r,n,10,t);auto p=r.odom.state().pose;float pe=std::hypot(p.x_mm-750,p.y_mm-400),ae=std::fabs(wrapAngle(p.theta_rad));v.push_back({"bezier_forward",ok&&pe<6&&ae<.06f,t,p,pe,deg(ae)});}{SimRobot r;Pose2D s{};s.theta_rad=s.theta_unwrapped_rad=kPi;r.setPose(s);Navigator n;n.commandBezier(r.odom.state().pose,{250,0},{450,-300},{700,-300},300,-1);float t;bool ok=run(r,n,10,t);auto p=r.odom.state().pose;float pe=std::hypot(p.x_mm-700,p.y_mm+300),ae=std::fabs(wrapAngle(p.theta_rad-kPi));v.push_back({"bezier_reverse",ok&&pe<7&&ae<.08f,t,p,pe,deg(ae)});}bool all=true;std::cout<<std::fixed<<std::setprecision(3)<<"scenario,pass,time_s,x_mm,y_mm,theta_deg,pos_error_mm,angle_error_deg\n";for(auto&r:v){all&=r.pass;std::cout<<r.name<<','<<(r.pass?"PASS":"FAIL")<<','<<r.t<<','<<r.p.x_mm<<','<<r.p.y_mm<<','<<deg(r.p.theta_rad)<<','<<r.pe<<','<<r.ae<<'\n';}return all?EXIT_SUCCESS:EXIT_FAILURE;}
