#include "diffnav.hpp"
namespace diffnav {
void DifferentialOdometry::reset(const Pose2D&p,int64_t r,int64_t l){s_={};s_.pose=p;s_.pose.theta_rad=wrapAngle(p.theta_rad);s_.right_ticks=r;s_.left_ticks=l;pr_=r;pl_=l;init_=true;}
void DifferentialOdometry::setPose(const Pose2D&p){s_.pose=p;s_.pose.theta_rad=wrapAngle(p.theta_rad);}
float DifferentialOdometry::rightTicksToDistance(int64_t t)const{return (float)t*c_.right_wheel_diameter_mm*kPi/(float)c_.counts_per_revolution;}
float DifferentialOdometry::leftTicksToDistance(int64_t t)const{return (float)t*c_.left_wheel_diameter_mm*kPi/(float)c_.counts_per_revolution;}
int64_t DifferentialOdometry::rightDistanceToTicks(float d)const{return std::llround(d*c_.counts_per_revolution/(c_.right_wheel_diameter_mm*kPi));}
int64_t DifferentialOdometry::leftDistanceToTicks(float d)const{return std::llround(d*c_.counts_per_revolution/(c_.left_wheel_diameter_mm*kPi));}
void DifferentialOdometry::update(int64_t r,int64_t l,float dt){if(!init_){reset(s_.pose,r,l);return;}if(!(dt>0)||dt>.1f){pr_=r;pl_=l;s_.right_ticks=r;s_.left_ticks=l;return;}int64_t drt=r-pr_,dlt=l-pl_;pr_=r;pl_=l;float dr=rightTicksToDistance(drt),dl=leftTicksToDistance(dlt),dc=.5f*(dr+dl),dth=(dr-dl)/c_.track_width_mm,th=s_.pose.theta_unwrapped_rad,xb=0,yb=0;if(std::fabs(dth)<1e-6f)xb=dc;else{float R=dc/dth;xb=R*std::sin(dth);yb=R*(1-std::cos(dth));}float co=std::cos(th),si=std::sin(th);s_.pose.x_mm+=co*xb-si*yb;s_.pose.y_mm+=si*xb+co*yb;s_.pose.theta_unwrapped_rad+=dth;s_.pose.theta_rad=wrapAngle(s_.pose.theta_unwrapped_rad);float a=dt/(c_.speed_filter_tau_s+dt);s_.wheel_speed.right_mm_s+=a*(dr/dt-s_.wheel_speed.right_mm_s);s_.wheel_speed.left_mm_s+=a*(dl/dt-s_.wheel_speed.left_mm_s);s_.body_velocity.linear_mm_s=.5f*(s_.wheel_speed.right_mm_s+s_.wheel_speed.left_mm_s);s_.body_velocity.angular_rad_s=(s_.wheel_speed.right_mm_s-s_.wheel_speed.left_mm_s)/c_.track_width_mm;s_.right_ticks=r;s_.left_ticks=l;}

void CubicBezierPath::set(Point2D a,Point2D b,Point2D c,Point2D d){p0_=a;p1_=b;p2_=c;p3_=d;arc_.fill(0);Point2D prev=p0_;for(int i=1;i<=N;i++){Point2D q=point((float)i/N);arc_[i]=arc_[i-1]+hypot2(q.x-prev.x,q.y-prev.y);prev=q;}valid_=arc_[N]>1e-3f;}
Point2D CubicBezierPath::point(float t)const{t=clampf(t,0,1);float m=1-t,m2=m*m,t2=t*t;return{m2*m*p0_.x+3*m2*t*p1_.x+3*m*t2*p2_.x+t2*t*p3_.x,m2*m*p0_.y+3*m2*t*p1_.y+3*m*t2*p2_.y+t2*t*p3_.y};}
Point2D CubicBezierPath::derivative(float t)const{t=clampf(t,0,1);float m=1-t;return{3*m*m*(p1_.x-p0_.x)+6*m*t*(p2_.x-p1_.x)+3*t*t*(p3_.x-p2_.x),3*m*m*(p1_.y-p0_.y)+6*m*t*(p2_.y-p1_.y)+3*t*t*(p3_.y-p2_.y)};}
Point2D CubicBezierPath::secondDerivative(float t)const{t=clampf(t,0,1);float m=1-t;return{6*m*(p2_.x-2*p1_.x+p0_.x)+6*t*(p3_.x-2*p2_.x+p1_.x),6*m*(p2_.y-2*p1_.y+p0_.y)+6*t*(p3_.y-2*p2_.y+p1_.y)};}
float CubicBezierPath::heading(float t)const{auto d=derivative(t);return std::atan2(d.y,d.x);}float CubicBezierPath::curvature(float t)const{auto a=derivative(t),b=secondDerivative(t);float s=a.x*a.x+a.y*a.y;if(s<1e-8f)return 0;return(a.x*b.y-a.y*b.x)/(s*std::sqrt(s));}
float CubicBezierPath::signedCrossTrack(float x,float y,float t)const{auto p=point(t),d=derivative(t);float n=hypot2(d.x,d.y);return n<1e-6f?0:(d.x*(y-p.y)-d.y*(x-p.x))/n;}
float CubicBezierPath::project(float x,float y,float hint)const{if(!valid_)return 0;int center=(int)std::lround(clampf(hint,0,1)*N),best=std::max(0,std::min(N,center)),lo=std::max(0,best-5),hi=std::min(N,best+9);float bd=1e30f;for(int i=lo;i<=hi;i++){float t=(float)i/N;auto p=point(t);float dx=p.x-x,dy=p.y-y,d=dx*dx+dy*dy;if(d<bd){bd=d;best=i;}}float t=(float)best/N;for(int k=0;k<4;k++){auto p=point(t),d=derivative(t),dd=secondDerivative(t);float rx=p.x-x,ry=p.y-y,f=rx*d.x+ry*d.y,fp=d.x*d.x+d.y*d.y+rx*dd.x+ry*dd.y;if(std::fabs(fp)<1e-7f)break;float n=clampf(t-f/fp,0,1);if(std::fabs(n-t)<1e-5f){t=n;break;}t=n;}return t;}
float CubicBezierPath::arcLengthAt(float t)const{t=clampf(t,0,1);float s=t*N;int i=std::min(N-1,(int)s);float f=s-i;return arc_[i]+f*(arc_[i+1]-arc_[i]);}

Navigator::Navigator(NavigatorConfig c):c_(c){stop();}void Navigator::stop(){st_={};st_.mode=MotionMode::IDLE;st_.result=MotionResult::IDLE;goto_=b_after_align_=false;vl_t_=va_t_=vl_=va_=0;settle_=0;}void Navigator::emergencyStop(FaultCode f){st_.mode=f==FaultCode::NONE?MotionMode::EMERGENCY_STOP:MotionMode::FAULT;st_.result=f==FaultCode::NONE?MotionResult::CANCELLED:MotionResult::FAULTED;st_.fault=f;goto_=b_after_align_=false;vl_t_=va_t_=vl_=va_=0;}void Navigator::clearEmergency(){stop();}
WheelSpeeds Navigator::body(float l,float a)const{return limitWheelSpeeds(bodyToWheels(l,clampf(a,-c_.max_angular_rate_rad_s,c_.max_angular_rate_rad_s),c_.track_width_mm),c_.max_wheel_speed_mm_s);}bool Navigator::stopped(const OdometryState&o)const{return std::fabs(o.wheel_speed.right_mm_s)<c_.stopped_speed_tolerance_mm_s&&std::fabs(o.wheel_speed.left_mm_s)<c_.stopped_speed_tolerance_mm_s;}void Navigator::succeeded(){st_.mode=MotionMode::IDLE;st_.result=MotionResult::SUCCEEDED;st_.fault=FaultCode::NONE;settle_=0;goto_=b_after_align_=false;}
void Navigator::commandVelocity(float l,float a){if(st_.mode==MotionMode::EMERGENCY_STOP||st_.mode==MotionMode::FAULT)return;goto_=b_after_align_=false;vl_t_=clampf(l,-c_.max_wheel_speed_mm_s,c_.max_wheel_speed_mm_s);va_t_=clampf(a,-c_.max_angular_rate_rad_s,c_.max_angular_rate_rad_s);st_.mode=MotionMode::VELOCITY;st_.result=MotionResult::RUNNING;}
void Navigator::beginLine(const Pose2D&p,Point2D t,float v,int dir){goto_=false;b_after_align_=false;ls_={p.x_mm,p.y_mm};lt_=t;float dx=t.x-ls_.x,dy=t.y-ls_.y;ll_=hypot2(dx,dy);if(ll_<1e-3f){succeeded();return;}lux_=dx/ll_;luy_=dy/ll_;lh_=std::atan2(dy,dx);lv_=clampf(v>0?v:c_.default_line_speed_mm_s,c_.line_min_speed_mm_s,c_.max_wheel_speed_mm_s);ldir_=dir>=0?1:-1;settle_=0;st_.mode=MotionMode::DRIVE_LINE;st_.result=MotionResult::RUNNING;}
void Navigator::commandMoveDistance(const Pose2D&p,float d,float v){beginLine(p,{p.x_mm+d*std::cos(p.theta_rad),p.y_mm+d*std::sin(p.theta_rad)},v,d>=0?1:-1);}void Navigator::commandRotateRelative(const Pose2D&p,float a,float v){goto_=b_after_align_=false;target_phi_u_=p.theta_unwrapped_rad+a;rot_len_=std::fabs(a)*c_.track_width_mm*.5f;rot_v_=v>0?std::min(v,c_.max_wheel_speed_mm_s):c_.rotate_wheel_speed_mm_s;settle_=0;st_.mode=MotionMode::ROTATE;st_.result=MotionResult::RUNNING;}void Navigator::commandOrientAbsolute(const Pose2D&p,float a,float v){commandRotateRelative(p,wrapAngle(a-p.theta_rad),v);}
void Navigator::commandGoTo(const Pose2D&p,float x,float y,float v,int dir,bool final,float phi){dir=dir>=0?1:-1;float dx=x-p.x_mm,dy=y-p.y_mm;if(hypot2(dx,dy)<=c_.position_tolerance_mm){if(final)commandOrientAbsolute(p,phi);else succeeded();return;}goto_=true;gt_={x,y};gv_=v>0?v:c_.default_line_speed_mm_s;gdir_=dir;gfinal_=final;gphi_=wrapAngle(phi);float ph=std::atan2(dy,dx),desired=wrapAngle(ph+(dir<0?kPi:0));target_phi_u_=p.theta_unwrapped_rad+wrapAngle(desired-p.theta_rad);rot_len_=std::fabs(target_phi_u_-p.theta_unwrapped_rad)*c_.track_width_mm*.5f;rot_v_=c_.rotate_wheel_speed_mm_s;settle_=0;st_.mode=MotionMode::ALIGN;st_.result=MotionResult::RUNNING;}
void Navigator::commandBezier(const Pose2D&p,Point2D p1,Point2D p2,Point2D p3,float v,int dir){dir=dir>=0?1:-1;goto_=false;bp_.set({p.x_mm,p.y_mm},p1,p2,p3);if(!bp_.valid()){emergencyStop(FaultCode::INVALID_COMMAND);return;}bt_=0;bv_=v>0?v:c_.default_bezier_speed_mm_s;bdir_=dir;b_after_align_=true;float desired=wrapAngle(bp_.heading(0)+(dir<0?kPi:0));target_phi_u_=p.theta_unwrapped_rad+wrapAngle(desired-p.theta_rad);rot_len_=std::fabs(target_phi_u_-p.theta_unwrapped_rad)*c_.track_width_mm*.5f;rot_v_=c_.rotate_wheel_speed_mm_s;settle_=0;st_.mode=MotionMode::ALIGN;st_.result=MotionResult::RUNNING;}
WheelSpeeds Navigator::align(const OdometryState&o){float e=target_phi_u_-o.pose.theta_unwrapped_rad,rem=std::fabs(e)*c_.track_width_mm*.5f;st_.heading_error_rad=e;st_.remaining_mm=rem;if(std::fabs(e)<=c_.align_tolerance_rad&&stopped(o)){if(goto_){auto t=gt_;float v=gv_;int d=gdir_;beginLine(o.pose,t,v,d);goto_=true;return{};}if(b_after_align_){b_after_align_=false;st_.mode=MotionMode::FOLLOW_BEZIER;return{};}succeeded();return{};}float prog=std::max(0.0f,rot_len_-rem),wv=profileSpeed(prog,rem,rot_v_,c_.rotate_accel_mm_s2,c_.rotate_decel_mm_s2,c_.rotate_min_wheel_speed_mm_s);if(rem<8)wv=std::min(wv,120.0f);return body(0,signf(e)*2*wv/c_.track_width_mm);}
WheelSpeeds Navigator::rotate(const OdometryState&o){float e=target_phi_u_-o.pose.theta_unwrapped_rad,rem=std::fabs(e)*c_.track_width_mm*.5f,prog=std::max(0.0f,rot_len_-rem);st_.progress_mm=prog;st_.remaining_mm=rem;st_.heading_error_rad=e;if(std::fabs(e)<=c_.heading_tolerance_rad&&stopped(o)){if(++settle_>=c_.settle_cycles){succeeded();return{};}}else settle_=0;if(rem<6)return body(0,clampf(c_.final_heading_kp*e,-2.5f,2.5f));float wv=profileSpeed(prog,rem,rot_v_,c_.rotate_accel_mm_s2,c_.rotate_decel_mm_s2,c_.rotate_min_wheel_speed_mm_s);return body(0,signf(e)*2*wv/c_.track_width_mm);}
WheelSpeeds Navigator::line(const OdometryState&o){float dx=o.pose.x_mm-ls_.x,dy=o.pose.y_mm-ls_.y,along=dx*lux_+dy*luy_,cross=lux_*dy-luy_*dx,ae=ll_-along,dist=hypot2(lt_.x-o.pose.x_mm,lt_.y-o.pose.y_mm),desired=wrapAngle(lh_+(ldir_<0?kPi:0)),he=wrapAngle(desired-o.pose.theta_rad);st_.progress_mm=clampf(along,0,ll_);st_.remaining_mm=dist;st_.cross_track_mm=cross;st_.heading_error_rad=he;bool pg=dist<=c_.position_tolerance_mm&&std::fabs(cross)<=c_.cross_track_tolerance_mm,hg=std::fabs(he)<=c_.heading_tolerance_rad;if(pg&&hg&&stopped(o)){if(++settle_>=c_.settle_cycles){if(goto_&&gfinal_){goto_=false;target_phi_u_=o.pose.theta_unwrapped_rad+wrapAngle(gphi_-o.pose.theta_rad);rot_len_=std::fabs(target_phi_u_-o.pose.theta_unwrapped_rad)*c_.track_width_mm*.5f;rot_v_=c_.rotate_wheel_speed_mm_s;settle_=0;st_.mode=MotionMode::FINAL_ORIENT;return{};}succeeded();return{};}}else settle_=0;if(dist<45){if(pg)return body(0,c_.final_heading_kp*he);float ph=std::atan2(lt_.y-o.pose.y_mm,lt_.x-o.pose.x_mm),dh=wrapAngle(ph+(ldir_<0?kPi:0)),pe=wrapAngle(dh-o.pose.theta_rad),scale=clampf(std::cos(pe),.2f,1.0f),lin=(float)ldir_*scale*std::min(c_.final_speed_limit_mm_s,std::max(18.0f,c_.final_position_kp_s_inv*dist));return body(lin,c_.final_heading_kp*pe);}float v=profileSpeed(std::max(0.0f,along),std::max(0.0f,ae),lv_,c_.line_accel_mm_s2,c_.line_decel_mm_s2,c_.line_min_speed_mm_s),lin=(float)ldir_*v,ca=std::atan2(c_.cross_track_gain_s_inv*cross,std::fabs(lin)+c_.stanley_softening_mm_s),omega=c_.heading_kp*he-(float)ldir_*c_.stanley_gain*ca;return body(lin,omega);}
WheelSpeeds Navigator::bezier(const OdometryState&o){bt_=bp_.project(o.pose.x_mm,o.pose.y_mm,bt_);float prog=bp_.arcLengthAt(bt_),rem=std::max(0.0f,bp_.totalLength()-prog);auto end=bp_.point(1);float ed=hypot2(end.x-o.pose.x_mm,end.y-o.pose.y_mm),th=bp_.heading(bt_),desired=wrapAngle(th+(bdir_<0?kPi:0)),he=wrapAngle(desired-o.pose.theta_rad),cross=bp_.signedCrossTrack(o.pose.x_mm,o.pose.y_mm,bt_);st_.progress_mm=prog;st_.remaining_mm=ed;st_.cross_track_mm=cross;st_.heading_error_rad=he;if(rem<25||bt_>.985f){float finalh=wrapAngle(bp_.heading(1)+(bdir_<0?kPi:0));int d=bdir_;beginLine(o.pose,end,c_.final_speed_limit_mm_s,d);goto_=true;gfinal_=true;gphi_=finalh;return{};}float v=profileSpeed(prog,rem,bv_,c_.bezier_accel_mm_s2,c_.bezier_decel_mm_s2,c_.bezier_min_speed_mm_s),lin=(float)bdir_*v,ca=std::atan2(c_.cross_track_gain_s_inv*cross,v+c_.stanley_softening_mm_s),omega=bp_.curvature(bt_)*v+c_.heading_kp*he-(float)bdir_*c_.stanley_gain*ca;return body(lin,omega);}
WheelSpeeds Navigator::update(const OdometryState&o,float dt){if(!(dt>0))return{};switch(st_.mode){case MotionMode::IDLE:case MotionMode::EMERGENCY_STOP:case MotionMode::FAULT:return{};case MotionMode::VELOCITY:{float md=c_.line_accel_mm_s2*dt,ad=8*dt;vl_=clampf(vl_t_,vl_-md,vl_+md);va_=clampf(va_t_,va_-ad,va_+ad);return body(vl_,va_);}case MotionMode::ALIGN:return align(o);case MotionMode::DRIVE_LINE:return line(o);case MotionMode::FOLLOW_BEZIER:return bezier(o);case MotionMode::ROTATE:case MotionMode::FINAL_ORIENT:return rotate(o);}return{};}
}
