#include "encoder_pcnt.hpp"
#include "robot_config.hpp"
#include "diffnav.hpp"
#if defined(ESP_IDF_VERSION_MAJOR) && ESP_IDF_VERSION_MAJOR >= 5
bool EncoderPcnt::configureUnit(int a,int b,pcnt_unit_handle_t*u,pcnt_channel_handle_t*ca,pcnt_channel_handle_t*cb){pcnt_unit_config_t uc={};uc.high_limit=30000;uc.low_limit=-30000;uc.flags.accum_count=1;if(pcnt_new_unit(&uc,u)!=ESP_OK)return false;pcnt_chan_config_t ac={};ac.edge_gpio_num=a;ac.level_gpio_num=b;if(pcnt_new_channel(*u,&ac,ca)!=ESP_OK)return false;if(pcnt_channel_set_edge_action(*ca,PCNT_CHANNEL_EDGE_ACTION_INCREASE,PCNT_CHANNEL_EDGE_ACTION_DECREASE)!=ESP_OK)return false;if(pcnt_channel_set_level_action(*ca,PCNT_CHANNEL_LEVEL_ACTION_KEEP,PCNT_CHANNEL_LEVEL_ACTION_INVERSE)!=ESP_OK)return false;pcnt_chan_config_t bc={};bc.edge_gpio_num=b;bc.level_gpio_num=a;if(pcnt_new_channel(*u,&bc,cb)!=ESP_OK)return false;if(pcnt_channel_set_edge_action(*cb,PCNT_CHANNEL_EDGE_ACTION_DECREASE,PCNT_CHANNEL_EDGE_ACTION_INCREASE)!=ESP_OK)return false;if(pcnt_channel_set_level_action(*cb,PCNT_CHANNEL_LEVEL_ACTION_KEEP,PCNT_CHANNEL_LEVEL_ACTION_INVERSE)!=ESP_OK)return false;pcnt_glitch_filter_config_t f={};f.max_glitch_ns=robot_config::kEncoderGlitchFilterNs;if(pcnt_unit_set_glitch_filter(*u,&f)!=ESP_OK)return false;if(pcnt_unit_add_watch_point(*u,uc.high_limit)!=ESP_OK||pcnt_unit_add_watch_point(*u,uc.low_limit)!=ESP_OK)return false;return pcnt_unit_enable(*u)==ESP_OK&&pcnt_unit_clear_count(*u)==ESP_OK&&pcnt_unit_start(*u)==ESP_OK;}
bool EncoderPcnt::begin(){return configureUnit(robot_config::kRightEncoderAPin,robot_config::kRightEncoderBPin,&ru_,&rca_,&rcb_)&&configureUnit(robot_config::kLeftEncoderAPin,robot_config::kLeftEncoderBPin,&lu_,&lca_,&lcb_);}EncoderCounts EncoderPcnt::snapshot(){int r=0,l=0;if(ru_)pcnt_unit_get_count(ru_,&r);if(lu_)pcnt_unit_get_count(lu_,&l);return{(int64_t)robot_config::kRightEncoderSign*r,(int64_t)robot_config::kLeftEncoderSign*l};}void EncoderPcnt::clear(){if(ru_)pcnt_unit_clear_count(ru_);if(lu_)pcnt_unit_clear_count(lu_);}
#else
bool EncoderPcnt::configureUnit(pcnt_unit_t u,int a,int b){pcnt_config_t x={};x.pulse_gpio_num=a;x.ctrl_gpio_num=b;x.unit=u;x.channel=PCNT_CHANNEL_0;x.pos_mode=PCNT_COUNT_INC;x.neg_mode=PCNT_COUNT_DEC;x.lctrl_mode=PCNT_MODE_KEEP;x.hctrl_mode=PCNT_MODE_REVERSE;x.counter_h_lim=30000;x.counter_l_lim=-30000;if(pcnt_unit_config(&x)!=ESP_OK)return false;pcnt_config_t y={};y.pulse_gpio_num=b;y.ctrl_gpio_num=a;y.unit=u;y.channel=PCNT_CHANNEL_1;y.pos_mode=PCNT_COUNT_DEC;y.neg_mode=PCNT_COUNT_INC;y.lctrl_mode=PCNT_MODE_KEEP;y.hctrl_mode=PCNT_MODE_REVERSE;y.counter_h_lim=30000;y.counter_l_lim=-30000;if(pcnt_unit_config(&y)!=ESP_OK)return false;uint32_t cycles=(robot_config::kEncoderGlitchFilterNs*80U+999U)/1000U;cycles=std::max<uint32_t>(1,std::min<uint32_t>(1023,cycles));if(pcnt_set_filter_value(u,(uint16_t)cycles)!=ESP_OK||pcnt_filter_enable(u)!=ESP_OK)return false;return pcnt_counter_pause(u)==ESP_OK&&pcnt_counter_clear(u)==ESP_OK&&pcnt_counter_resume(u)==ESP_OK;}
bool EncoderPcnt::begin(){rt_=lt_=0;pr_=pl_=0;return configureUnit(PCNT_UNIT_0,robot_config::kRightEncoderAPin,robot_config::kRightEncoderBPin)&&configureUnit(PCNT_UNIT_1,robot_config::kLeftEncoderAPin,robot_config::kLeftEncoderBPin);}EncoderCounts EncoderPcnt::snapshot(){int16_t r=0,l=0;pcnt_get_counter_value(PCNT_UNIT_0,&r);pcnt_get_counter_value(PCNT_UNIT_1,&l);rt_+=(int64_t)robot_config::kRightEncoderSign*diffnav::extendLegacyPcntDelta(pr_,r);lt_+=(int64_t)robot_config::kLeftEncoderSign*diffnav::extendLegacyPcntDelta(pl_,l);pr_=r;pl_=l;return{rt_,lt_};}void EncoderPcnt::clear(){pcnt_counter_clear(PCNT_UNIT_0);pcnt_counter_clear(PCNT_UNIT_1);rt_=lt_=0;pr_=pl_=0;}
#endif
