#include "ros_bridge.hpp"
#include <micro_ros_platformio.h>
#include <rcl/rcl.h>
#include <rclc/executor.h>
#include <rclc/rclc.h>
#include <rmw_microros/rmw_microros.h>
#include <geometry_msgs/msg/pose2_d.h>
#include <geometry_msgs/msg/twist.h>
#include <std_msgs/msg/bool.h>
#include "robot_config.hpp"
namespace {
QueueHandle_t cq=nullptr,tq=nullptr;rcl_allocator_t alloc;rclc_support_t support;rcl_node_t node;rcl_publisher_t pose_pub;rcl_subscription_t vel_sub,goal_sub,estop_sub;rclc_executor_t exec;geometry_msgs__msg__Pose2D pose_msg,goal_msg;geometry_msgs__msg__Twist vel_msg;std_msgs__msg__Bool estop_msg;bool ready=false,sup=false,nod=false,pub=false,vs=false,gs=false,es=false,ex=false;
void enqueue(const diffnav::NavCommand&c){if(!cq)return;if(xQueueSend(cq,&c,0)!=pdTRUE){diffnav::NavCommand old{};xQueueReceive(cq,&old,0);xQueueSend(cq,&c,0);}}
void velCb(const void*m){auto*msg=(const geometry_msgs__msg__Twist*)m;diffnav::NavCommand c{};c.type=diffnav::NavCommandType::VELOCITY;c.p0=msg->linear.x*1000.0;c.p1=msg->angular.z;enqueue(c);}void goalCb(const void*m){auto*msg=(const geometry_msgs__msg__Pose2D*)m;diffnav::NavCommand c{};c.type=diffnav::NavCommandType::GO_TO;c.p0=msg->x*1000.0;c.p1=msg->y*1000.0;c.p3=msg->theta;c.direction=1;c.use_final_heading=true;enqueue(c);}void estopCb(const void*m){auto*msg=(const std_msgs__msg__Bool*)m;diffnav::NavCommand c{};c.type=msg->data?diffnav::NavCommandType::EMERGENCY_STOP:diffnav::NavCommandType::CLEAR_EMERGENCY;enqueue(c);}
void destroy(){if(sup){rmw_context_t* rmw_context=rcl_context_get_rmw_context(&support.context);if(rmw_context)rmw_uros_set_context_entity_destroy_session_timeout(rmw_context,0);}if(ex)rclc_executor_fini(&exec);if(es&&nod)(void)rcl_subscription_fini(&estop_sub,&node);if(gs&&nod)(void)rcl_subscription_fini(&goal_sub,&node);if(vs&&nod)(void)rcl_subscription_fini(&vel_sub,&node);if(pub&&nod)(void)rcl_publisher_fini(&pose_pub,&node);if(nod)(void)rcl_node_fini(&node);if(sup)rclc_support_fini(&support);ready=sup=nod=pub=vs=gs=es=ex=false;}
bool create(){alloc=rcl_get_default_allocator();support={};node=rcl_get_zero_initialized_node();pose_pub=rcl_get_zero_initialized_publisher();vel_sub=rcl_get_zero_initialized_subscription();goal_sub=rcl_get_zero_initialized_subscription();estop_sub=rcl_get_zero_initialized_subscription();exec=rclc_executor_get_zero_initialized_executor();if(rclc_support_init(&support,0,nullptr,&alloc)!=RCL_RET_OK)return false;sup=true;if(rclc_node_init_default(&node,"diffnav_esp32","",&support)!=RCL_RET_OK)return false;nod=true;if(rclc_publisher_init_best_effort(&pose_pub,&node,ROSIDL_GET_MSG_TYPE_SUPPORT(geometry_msgs,msg,Pose2D),"/robot_pose_raw")!=RCL_RET_OK)return false;pub=true;if(rclc_subscription_init_best_effort(&vel_sub,&node,ROSIDL_GET_MSG_TYPE_SUPPORT(geometry_msgs,msg,Twist),"/cmd_vel")!=RCL_RET_OK)return false;vs=true;if(rclc_subscription_init_default(&goal_sub,&node,ROSIDL_GET_MSG_TYPE_SUPPORT(geometry_msgs,msg,Pose2D),"/nav/goal")!=RCL_RET_OK)return false;gs=true;if(rclc_subscription_init_default(&estop_sub,&node,ROSIDL_GET_MSG_TYPE_SUPPORT(std_msgs,msg,Bool),"/nav/emergency_stop")!=RCL_RET_OK)return false;es=true;if(rclc_executor_init(&exec,&support.context,3,&alloc)!=RCL_RET_OK)return false;ex=true;if(rclc_executor_add_subscription(&exec,&vel_sub,&vel_msg,&velCb,ON_NEW_DATA)!=RCL_RET_OK||rclc_executor_add_subscription(&exec,&goal_sub,&goal_msg,&goalCb,ON_NEW_DATA)!=RCL_RET_OK||rclc_executor_add_subscription(&exec,&estop_sub,&estop_msg,&estopCb,ON_NEW_DATA)!=RCL_RET_OK)return false;ready=true;return true;}
}
void rosBridgeTask(void*arg){auto ctx=*(RosBridgeContext*)arg;cq=ctx.command_queue;tq=ctx.telemetry_queue;set_microros_serial_transports(Serial);vTaskDelay(pdMS_TO_TICKS(1500));uint32_t last_try=0,last_pub=0,last_ping=0;TelemetryFrame f{};for(;;){uint32_t now=millis();if(!ready){if(now-last_try>=1000){last_try=now;if(rmw_uros_ping_agent(50,1)==RMW_RET_OK&&!create())destroy();}vTaskDelay(pdMS_TO_TICKS(20));continue;}if(rclc_executor_spin_some(&exec,RCL_MS_TO_NS(robot_config::kRosSpinPeriodMs))!=RCL_RET_OK){destroy();continue;}while(tq&&xQueueReceive(tq,&f,0)==pdTRUE){}if(now-last_pub>=robot_config::kTelemetryPeriodMs){last_pub=now;pose_msg.x=f.odom.pose.x_mm/1000.0;pose_msg.y=f.odom.pose.y_mm/1000.0;pose_msg.theta=f.odom.pose.theta_rad;if(rcl_publish(&pose_pub,&pose_msg,nullptr)!=RCL_RET_OK){destroy();continue;}}if(now-last_ping>=1000){last_ping=now;if(rmw_uros_ping_agent(25,1)!=RMW_RET_OK)destroy();}vTaskDelay(pdMS_TO_TICKS(1));}}
